export const projects = [
    {
      title: 'Face Recognition App',
      description: "Face recognition app is a technology-based application that identifies individuals from images or videos by comparing facial features of the subject with a database of stored faces. The app typically uses deep learning algorithms to analyze the facial features, extract relevant information, and match it with the stored images.",
      image: 'https://i.imgur.com/55AXLAG.png',
      tags: ['Python', 'Django',],
      source: 'https://github.com/Janajan-Jeyabalan/FaceRecognitionApp',
      visit: 'https://github.com/Janajan-Jeyabalan/FaceRecognitionApp',
      id: 0,
    },
    {
      title: 'The Next Generation Payment Method',
      description:"A next-generation payment method application is a software tool that facilitates the use of advanced payment methods, such as digital wallets, biometric authentication, and blockchain technology. The application is designed to be user-friendly and secure, offering a seamless payment experience for both consumers and merchants.",
      image: 'https://i.imgur.com/zBCoQiw.png',      
      tags: ['React', 'JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/Janajan-Jeyabalan/The-Next-Generation-Payment-Method',
      visit: 'https://github.com/Janajan-Jeyabalan/The-Next-Generation-Payment-Method',
      id: 1,
    },
    {
      title: 'SneakPeek Application',
      description: "SneakPeek is a sneaker release calendar application is a tool for sneaker enthusiasts to stay up-to-date on the latest sneaker releases from their favorite brands. The app provides a comprehensive and regularly updated calendar of upcoming sneaker releases, including information on the style, colorway, price, and availability.",
      image: 'https://i.imgur.com/zblQcIa.png',
      tags: ['React', 'JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/Janajan-Jeyabalan/sneakpeek_application',
      visit: 'https://github.com/Janajan-Jeyabalan/sneakpeek_application',
      id: 2,
    },
    {
      title: 'Firebase Cloud Messaging App',
      description: "Firebase Cloud Messaging (FCM) is a cross-platform messaging solution from Google that allows app developers to send notifications and messages to users on Android, iOS, and web. The FCM app serves as a central hub for sending messages and notifications to users, enabling developers to target specific audience segments and send personalized messages.",
      image: 'https://i.imgur.com/2Sdr0OG.png',
      tags: ['Firbase', 'Java', 'Android Studio' ],
      source: 'https://github.com/Janajan-Jeyabalan/Firebase-Cloud-Messaging-App',
      visit: 'https://github.com/Janajan-Jeyabalan/Firebase-Cloud-Messaging-App',
      id: 3,
    },
    {
      title: 'Jeopardy Application',
      description: "Jeopardy game application is a digital version of the popular TV quiz show. The app simulates the experience of playing Jeopardy, offering users a chance to test their knowledge on various categories such as history, science, literature, and pop culture. The app features a game board with multiple categories and dollar amounts, and users select a category and dollar amount to answer a question.",
      image: 'https://i.imgur.com/C2VtmF3.png',
      tags: ['C'],
      source: 'https://github.com/Janajan-Jeyabalan/JeopardyOS',
      visit: 'https://github.com/Janajan-Jeyabalan/JeopardyOS',
      id: 3,
    },
  ];
  
  export const TimeLineData = [
    { year: 2018, text: 'Started My Journey', },
    { year: 2019, text: 'Worked As A Freelance Developer', },
    { year: 2020, text: 'Founded Klothelabel', },
    { year: 2021, text: 'Royal Brokers Corporation Internship', },
    { year: 2022, text: 'Founded Road Surface Deterioration AI/ML Application', },
    { year: 2023, text: 'Software Developer @ CRA', },
    { year: '2024-2025', text: "Software Developer Project Lead @ CRA", },
  ];